### ISSUE TITLE
No such file or directory: 'testes/styles.css'

### ISSUE THREAD

**Issue by daneoshiga** [eduardocl/rss2kindle.py#1]
Tentei usar como explicado no Readme, mas aparentemente está dependendo de arquivos que estão no .gitignore, 

Está reclamando da falta do arquivo testes/styles.css, e a pasta testes está no gitignore.

```
Traceback (most recent call last):
  File "rss2kindle.py", line 422, in <module>
    epub.save(epubfile)
  File "rss2kindle.py", line 298, in save
    epubfile.write("testes/styles.css", "styles.css")
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: 'testes/styles.css'
```

**Comment by eduardocl** [comment]
@daneoshiga, obrigado por avisar, já corrigi. Tentei fazer um teste com um css para formatar o texto e comitei sem terminar. Isso que dá programar tomando uma geladinha :-). Inclusive, estou pensando em fazer uma segunda versão (assim que arrumar tempo), com uma linha de comando para adicionar e excluir feeds e, gerar o arquivo somente com os feeds escolhidos por que o arquivo final (.mobi) está ficando muito grande e o kindle não está lendo.

**Comment by daneoshiga** [comment]
legal cara, to muito sem tempo senão tentava ajudar, uma opção poderia ser também definir um range de dias pra ele considerar, ou de postagens de cada feed...

**Comment by eduardocl** [comment]
Na verdade eu to dedicando um tempo (bem pouco mesmo) para outro projeto que estou escrevendo em python, o [rkb](https://github.com/eduardocl/rkb) - [telas](https://github.com/eduardocl/rkb/tree/master/screenshots), onde eu armazendo arquivos pdf, docs, textos, etc e indexo no solr. Resolvi escrevê-lo em python para aprender mais sobre a linguagem, bottle.py e a facilidade com que encontro python em qualquer unix. Com rails eu estava tendo problemas a cada atualização. Eu perdia mais tempo apanhando paras as gems do que programando :-).
